services:

  backend:
    build: .

    ports:
      - "5500:5500"

    env_file:
      - .env

    environment:
      MONGO_URI: mongodb://mongodb:27017/smartExpenseTracker

    depends_on:
      - mongodb

    volumes:
      - .:/app

    working_dir: /app/server

    command: node server.js

  mongodb:
    image: mongo:8

    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    external: true
    name: project-4expensetracker_mongo-data
